### ISSUE TITLE
Installation issues with root_numpy and clang

### ISSUE THREAD

**Issue by uzzielperez** [scikit-hep/root_numpy#305]
Hi! 

I've been trying to install root_numpy. I have already updated my gcc to the latest version and have gotten past the "missing atomic file" but now a new error appears after I built numpy with gcc-6.  
Here is a part of the error I got. 

```
[`/Users/DC/Downloads/build/include/TClassEdit.h:181:45: error: 'TClassEdit::GetUniquePtrType' declared as an 'inline' variable
    inline std::string GetUniquePtrType(std::string_view name)
                                             ^~~~~~~~~~~
/Users/DC/Downloads/build/include/TClassEdit.h:181:40: error: 'string_view' is not a member of 'std'
    inline std::string GetUniquePtrType(std::string_view name)
                                        ^~~
/Users/DC/Downloads/build/include/TClassEdit.h:182:4: error: expected ',' or ';' before '{' token
    {
    ^
error: command 'gcc' failed with exit status 1`](url)
```

**Comment by ndawe** [comment]
Hi @uzzielperez! Which version of ROOT is this? There have been issues compiling ROOT with gcc6 in the past: https://sft.its.cern.ch/jira/browse/ROOT-8139

**Comment by uzzielperez** [comment]
Hi @ndawe! Thanks for your reply! I'm using ROOT v6.08.02. I forgot to tell that I am using MacOS. Someone told me that I should be using clang instead. I don't really understand what that means. 

I think my problem is I should build numpy properly first. Should I reinstall anaconda to do that or could I just build numpy separately and then build root_numpy?

**Comment by uzzielperez** [comment]
Hi @ndawe, I reinstalled bumpy using pip2 install numpy and then built ROOT v6.08.02 using cmake. 
And then inside the git cloned root_numpy directory I did 
`sudo ROOTSYS=$ROOTSYS python setup.py install`
but I get the following error
`/Users/up/Downloads/build/include/Rtypes.h:37:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
`
Do you have an idea on why this happens?

**Comment by ndawe** [comment]
Hmm.. seems like c++11 is disabled somewhere. Can you try placing this in the setup.py?

```
140     extra_compile_args=root_cflags + [
141         '-Wno-unused-function',
142         '-Wno-write-strings',
NEW       '-std=c++11',
143     ],
````

root_numpy should automatically get that from root-config. When you build ROOT with cmake is c++11 enabled?

What do you see when running the following?

```
root-config --cflags
-pthread -std=c++11 -m64 -I/blabla/ROOT/v6-09-01/include/root
```

**Comment by kratsg** [comment]
@uzzielperez - were you able to get this fixed?

**Comment by ndawe** [comment]
Closing for now. Reopen if necessary.

**Comment by echurch** [comment]
This is the second time I've installed root_numpy on OSX10.12 and  have had to  turn to  the fix (with a ton of warnings that seem, in the end, harmless) at https://github.com/scikit-hep/root_numpy/issues/157
