### ISSUE TITLE
root_numpy documentation site

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/root_numpy#311]
On the page https://pypi.python.org/pypi/root_numpy, the "homepage" points to http://rootpy.github.io/root_numpy, which has been replaced by http://scikit-hep.org/root_numpy/ and is a broken link. Probably the same for rootpy.

Maybe you want the old link to continue working, rather than changing the link on PyPI.

**Comment by ndawe** [comment]
I'm not sure how to get http://rootpy.github.io/root_numpy to redirect to http://scikit-hep.org/root_numpy/ without creating a fork of root_numpy under rootpy and breaking the other automatic redirects within github.

**Comment by kratsg** [comment]
https://help.github.com/articles/redirects-on-github-pages/

Can we try setting up a fake-ish jekyll?

**Comment by ndawe** [comment]
Is that possible?

**Comment by ndawe** [comment]
I just updated the existing pypi record to point at http://scikit-hep.org/root_numpy/

**Comment by ndawe** [comment]
https://pypi.python.org/pypi/root_numpy/4.7.2
