### ISSUE TITLE
bug: root2array does not recognize file with single tree correctly

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/root_numpy#316]
It says in the documentation that one does not have to specify treename in the root2array call if the file contains only one tree. I have some files for which I get an error message if I do not specify treename, despite the fact that the file contains only a single unique tree. It seems to work for other files from the same set. I could not find a pattern.

**Comment by ndawe** [comment]
Do some files have subdirectories containing additional trees?

**Comment by HDembinski** [comment]
The files in my set are all produced with the same C++ code, which generates exactly one TTree for each file, and nothing else. There are no subdirectories.

**Comment by shir994** [comment]
I think I have experience related type of problem. I have a file of the following structure with only one tree inside.
File.root->Tree->Branches
After applying command
root_numpy.root2array("File.root", treename="Tree", branches=[...]) or just
root_numpy.root2array("File.root")

I get the following error

```python
/mnt/mfs/miniconda/envs/rep_py2/lib/python2.7/site-packages/root_numpy/_tree.pyc in root2array(filenames, treename, branches, selection, start, stop, step, include_weight, weight_name)
    203         start, stop, step,
    204         include_weight,
    205         weight_name)
    206 
    207     if flatten:

tree.pyx in _librootnumpy.root2array_fromFname (root_numpy/src/_librootnumpy.cpp:354)()

tree.pyx in _librootnumpy.tree2array (root_numpy/src/_librootnumpy.cpp:306)()

tree.pyx in _librootnumpy.handle_load (root_numpy/src/_librootnumpy.cpp:90)()

ValueError: chain is empty
```

Before update it works fine for me.

**Comment by ndawe** [comment]
@shir994 that looks like a separate issue. That error is raised when TChain::LoadTree() returns -1:

https://root.cern.ch/doc/master/classTChain.html#a2ee8505dfdc27b4a8e964844c5b754b7

So the chain must not contain any trees, or there is some other ROOT bug or corruption of the file.

**Comment by ndawe** [comment]
@shir994 please open a new issue, and it would help if you are able to provide me the offending file.

**Comment by ndawe** [comment]
@HDembinski I bet there must be multiple cycles of the tree written in some files (multiple TKeys with the same name). The new implementation of list_trees does not remove duplicates. I'll fix that.

**Comment by shir994** [comment]
@ndawe You are right, the file was corrupted by some reason. Everything works fine now.

**Comment by HDembinski** [comment]
@ndawe That could be. I didn't check for multiple cycles, but since the files do not have the same number of events, it is likely the reason.

**Comment by ndawe** [comment]
Indeed. It's failing to remove duplicate keys. Fixing it now.

**Comment by HDembinski** [comment]
Thanks! :D
