### ISSUE TITLE
feature request: chunked reading of branches

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/root_numpy#317]
I have a tree which contains branches of varlen arrays, describing aspects of recorded tracks for that event, like momentum, etc. Per event, these varlen arrays are short. Therefore, iterating over events and processing the varlen arrays as numpy arrays per event is not efficient.

It would be nice if there was a second way to read branches that behaves more like TTree::Draw which allows you to process larger chunks of these track variables at a time, collected internally by root_numpy over several events. In this mode, selections should also work like in TTree::Draw: a selection on a varlen array that describes a track variable should be applied to other varlen arrays of the same length.

Example: with TTree::Draw, I can do this:

```
mytree.Draw("track_momentum", "track_pid == 22") # 22 is a photon
```

where "track_momentum" and "track_pid" are varlen arrays. This will show only the momentum distribution of photons.

The interface I suggest would look like this:

```
array = root2array("some_file.root", branches=["track_momentum"], selection="track_pid==22", chunk=4096)
for a in array: # iterate over chunks with 4096 entries of "track_momentum" values until the tree is exhausted
     # do something with a["track_momentum"], which is an array of length 4096
```

**Comment by ndawe** [comment]
Interesting... still thinking about various approaches here.

First, can you check if you get good performance with these already existing features?

```python
array = root2array("some_file.root", branches=('track_momentum', -10, 100), selection="track_pid==22").reshape(-1)
```

('track_momentum', -10, 100) tells root_numpy to consider that varlen array branch as a fixed-length array branch with 100 entries per event and default value of -10 for the arrays that are shorter than 100. Arrays longer than 100 are cropped, so you want to set that high enough that cropping does not occur, but not too high such that there is a lot of wasted space in the output array. reshape(-1) will then transform the 2D array into a 1D array of all photon momenta.

Or you can use root_numpy's stretch function to join each varlength subarray into a 1D array:

```python
from root_numpy import stretch
array = stretch(root2array("some_file.root", branches=['track_momentum'], selection="track_pid==22"), fields='track_momentum')
```

**Comment by ndawe** [comment]
Examples:

```python
>>> from root_numpy import stretch, root2array
>>> from root_numpy.testdata import get_filepath
>>>
>>> root2array(get_filepath('vary1.root'), branches=('f_float', -10, 100), selection='n_int % 2 ==0').reshape(-1)
array([ 20.5,  22.5, -10. , ..., -10. , -10. , -10. ], dtype=float32)
>>> stretch(root2array(get_filepath('vary1.root'), branches=['f_float'], selection='n_int % 2 ==0'), fields='f_float')
array([  20.5,   22.5,   40.5,   42.5,   44.5,   60.5,   62.5,   64.5,
         66.5,   80.5,   82.5,   84.5,   86.5,   88.5,  100.5,  102.5,
        104.5,  106.5,  108.5,  110.5,  120.5,  122.5,  124.5,  126.5,
        128.5,  130.5,  132.5,  140.5,  142.5,  144.5,  146.5,  148.5,
        150.5,  152.5,  154.5,  160.5,  162.5,  164.5,  166.5,  168.5,
        170.5,  172.5,  174.5,  176.5,  180.5,  182.5,  184.5,  186.5,
        188.5,  190.5,  192.5,  194.5,  196.5,  198.5,  200.5,  202.5,
        204.5,  206.5,  208.5,  210.5,  212.5,  214.5,  216.5,  218.5,
        220.5,  220.5,  222.5,  224.5,  226.5,  228.5,  230.5,  232.5,
        234.5,  236.5,  238.5,  240.5,  242.5,  240.5,  242.5,  244.5,
        246.5,  248.5,  250.5,  252.5,  254.5,  256.5,  258.5,  260.5,
        262.5,  264.5,  260.5,  262.5,  264.5,  266.5,  268.5,  270.5,
        272.5,  274.5,  276.5,  278.5,  280.5,  282.5,  284.5,  286.5,
        280.5,  282.5,  284.5,  286.5,  288.5,  290.5,  292.5,  294.5,
        296.5,  298.5,  300.5,  302.5,  304.5,  306.5,  308.5,  300.5,
        302.5,  304.5,  306.5,  308.5,  310.5,  312.5,  314.5,  316.5,
        318.5,  320.5,  322.5,  324.5,  326.5,  328.5,  330.5,  320.5,
        322.5,  324.5,  326.5,  328.5,  330.5,  332.5,  334.5,  336.5,
        338.5,  340.5,  342.5,  344.5,  346.5,  348.5,  350.5,  352.5,
        340.5,  342.5,  344.5,  346.5,  348.5,  350.5,  352.5,  354.5,
        356.5,  358.5,  360.5,  362.5,  364.5,  366.5,  368.5,  370.5,
        372.5,  374.5,  360.5,  362.5,  364.5,  366.5,  368.5,  370.5,
        372.5,  374.5,  376.5,  378.5,  380.5,  382.5,  384.5,  386.5,
        388.5,  390.5,  392.5,  394.5,  396.5,  380.5,  382.5,  384.5,
        386.5,  388.5,  390.5,  392.5,  394.5,  396.5,  398.5,  400.5,
        402.5,  404.5,  406.5,  408.5,  410.5,  412.5,  414.5,  416.5,
        418.5], dtype=float32)
```

**Comment by HDembinski** [comment]
Hi, I am glad that you find this proposal interesting! I should be quite able to implement the feature myself, I just wanted to gauge the interest in such a feature.

I think we don't need benchmarks to see that the chunked version must be much faster. The buffer for a chunk only needs to be allocated once (de/allocation is expensive) and the chunking the reads from the TTree makes the code do more in fast C++ and less in the slow Python loop. At least in my case, where I have many events with comparably short varlen arrays, I bet you any money that chunked reading is going to be much faster.

The other solutions you suggested are not safe to use:
- fix array size in advance for varlen branch: what happens when the varlen array happens to be larger than 100 for a particular event? What if it is typically much smaller, and I am wasting performance?
- use stretch: what if I load a very large file where the array produced by stretch does not fit into memory?

Next to speed, however, there is a more pressing concern. The current implementation of root2array does not work when you select on varlen arrays.

The following code
```
array = root_numpy.root2array(fn, branches="mc_trk_pz", selection="mc_trk_pz<1")
n = 0
for a in array:
    n += len(a)
print nphotons # prints 12624, while the correct number is 254
```

**Comment by ndawe** [comment]
True chunked should be much faster.

Also if the array would be larger than memory, you can use the start and stop arguments to iteratively process chunks that are small enough.

**Comment by ndawe** [comment]
Ah, for the selection you should use the ``object_selection`` argument instead of ``selection``. Sorry for not correcting that above. selection will include all entries where the selection evaluates to true for at least one element per entry, but object_selection will operate on the subarrays.

**Comment by ndawe** [comment]
```python
array = root_numpy.root2array(fn, branches="mc_trk_pz", object_selection={"mc_trk_pz": "mc_trk_pz<1"})
```

**Comment by HDembinski** [comment]
Ah, I see, thank you! This was not clear in the documentation.

Perhaps it would make sense to throw a warning if the user tries to use selection=... with a varlen branch?

**Comment by ndawe** [comment]
I've improved the documentation of selection and object_selection:

http://scikit-hep.org/root_numpy/reference/generated/root_numpy.root2array.html#root_numpy.root2array

There are times when selection= with array-type branches is intentional and valid (say I want entries where at least one subelement satisfies a condition) so a warning might become annoying.

**Comment by eduardo-rodrigues** [comment]
Since this package is deprecated and we will eventually archive it in 2020, shall we try and close the outstanding enhancements that simply won't be done? @HDembinski, this can be closed at this point, right?

**Comment by HDembinski** [comment]
Yes.
