### ISSUE TITLE
Reading of ROOT vector branches - 1D array inside 1D array

### ISSUE THREAD

**Issue by imoric** [scikit-hep/root_numpy#323]
Wondering if it is possible to read vector ROOT branches, 1D arrays of 1D arrays.
root_numpy seems to combine all the _second degree_ 1D arrays inside the _first degree_ 1D array, or am I missing something?

**Comment by ndawe** [comment]
Yes, ``vector<T>`` and ``vector<vector<T> >`` are supported where ``T`` is some primitive type.

**Comment by ndawe** [comment]
``vector<T>`` gives you a column like ``[[a, b, c], [d, e]]``
``vector<vector<T> >``  gives you a column like ``[[[a, b], [c, d, e, f]], [[g]], [[h, i]]]``

**Comment by ndawe** [comment]
Can you show a specific case where root_numpy is giving you something unexpected?

**Comment by imoric** [comment]
OK, just checked. Feel free to delete the thread. 
The issue is with the ROOT file, all the vectors are bunched together.
Thank you!

**Comment by ndawe** [comment]
No problem!
