### ISSUE TITLE
joss review: nose tests need a clean directory to run

### ISSUE THREAD

**Issue by wlav** [scikit-hep/root_numpy#327]
Going through the installation instructions in the given order, one can not run the tests directly after running install, as "from . import _librootnumpy" fails.

Following the Makefile ("make test"), I note that that creates a clean directory and enters it, before running the tests. Doing the same allows nosetests to run.

Can such a line (e.g. "mkdir nose && cd nose") be added for running nosetests?

**Comment by ndawe** [comment]
``nosetests --exe -s -v root_numpy`` is to be run from outside the source directory (mentioned in the docs i.e. after a pip install) while "make test" is a shortcut for developers for testing within the source directory.

**Comment by ndawe** [comment]
This would be the usual way a user would run the tests after an installation:

```
pip install --user root_numpy
nosetests --exe -s -v root_numpy
```

I'll clarify this in the docs so that those installing from source instead use "make test" inside the source directory.

**Comment by wlav** [comment]
Ah, I missed that line about running outside the source directory. I went c&p through the code lines (git, setup.py, nosetests) and b/c of the 2nd step was still in the source directory when running the test. Then did 'make test' to find that that did work ...

**Comment by ndawe** [comment]
Clarified in #340
