### ISSUE TITLE
joss review: confusing line in tutorial

### ISSUE THREAD

**Issue by wlav** [scikit-hep/root_numpy#330]
This line had me puzzled:

filename = get_filepath('test.root')

b/c it's not clear that it is locating a file, as opposed to, say, creating or just constructing a temporary (unique) file name. Reading on, it's clear that it must to location, as the tree must exist.

Worth it to add a comment (there are several already anyway and this is a root_numpy API after all) and/or print 'filename' which makes it completely clear. Similarly, intree.Print() may be helpful to understand the branch selection part better.

**Comment by wlav** [comment]
After reading the API list, I now see that get_filepath is NOT part of the API. Does prove clearly, it was confusing me. :) Maybe another option then is to keep the 'testdata' part of the name to make obvious what is going on here.

**Comment by ndawe** [comment]
Agreed. I'll use ``testdata.get_filepath()`` to make this clear.

**Comment by ndawe** [comment]
Fixed in #336
