### ISSUE TITLE
joss review: root_numpy FAQ example requires rootpy

### ISSUE THREAD

**Issue by wlav** [scikit-hep/root_numpy#331]
The FAQ has:

from rootpy import asrootpy
from rootpy.io import root_open

I'm not sure that rootpy is really germane to what is shown (the use of CloneTree() with disabled branches), but if it is considered so, then a link to (how to install) rootpy would be good. As is, having only followed the root_numpy installation instructions, the code fails (obviously).

**Comment by wlav** [comment]
same goes for the "Bootstrap a TTree with NumPy" example (although not the TMVA ones)

**Comment by ndawe** [comment]
Fixed in #342. The use of rootpy in the FAQ is removed. I've also mentioned the dependency on rootpy for the bootstrapping example (and pip installing rootpy).
