### ISSUE TITLE
doi for references

### ISSUE THREAD

**Issue by wlav** [scikit-hep/root_numpy#343]
The joss review requires references to have DOI's if available. The TMVA 2007 ACAT paper does not have one AFAICT, but there are more recent TMVA overview papers that do:

2010: doi:10.1088/1742-6596/219/3/03205
2012: doi:10.1063/1.4771869

The 2010 paper seems close to the 2007 one. The 2012 paper is less detailed (but probably more up-to-date for what it has).

The ROOT web-site no longer requests that references are made to the 1997 paper, so the most relevant paper for ROOT is AFAIK: doi:10.1016/j.cpc.2009.08.005.

The numpy folks request (https://scipy.org/citing.html): doi:10.1109/mcse.2011.37

**Comment by ndawe** [comment]
Fixed in #345. I also posted an updated preview of the paper here:

https://www.dropbox.com/s/ya16qx7qt88dqod/root_numpy.pdf?dl=0
