### ISSUE TITLE
Weight always 1.0 when using root2array 

### ISSUE THREAD

**Issue by vlisovsk** [scikit-hep/root_numpy#349]
Hello,
I have a simple code which is supposed to open the file _filename.root_, and copy to the array _data_array_ the following information: variables _B_P_, _B_PT_ and per-event weight _totWeight_: 

```
import root_numpy
columns = ['B_P','B_PT']
data_array = root_numpy.root2array('filename.root', treename='DecayTree', branches=columns, include_weight=True, weight_name='totWeight')
print(data_array)
```
And the output is 

```
(  53591.72056495,  3936.50385454,  1.)
( 175405.07927366,  11997.62799168,  1.)
...
```
where the last item (which is supposed to be the weight) turns always equal to 1 for all the events.
This should not be the case: the branch _totWeight_ (of the format Double_t) exists in the file _filename.root_ and contains the numbers which are not equal to one. I tried to use other variables as weights and the result is always the same.
It seems the weights are simply not read properly from the file.
Can someone please tell if I am doing something wrong here?

**Comment by ndawe** [comment]
If totWeight is a branch, then include it in the branches list. weight_name is what to label tree.GetWeight() in the output array. Makes sense? I'll make this more clear in the docs.

**Comment by kratsg** [comment]
> If totWeight is a branch, then include it in the branches list. weight_name is what to label tree.GetWeight() in the output array. Makes sense? I'll make this more clear in the docs.

This needs to be more clear. Looking at the source code for root2array implies that it will *not* add the specified weight branch to the list of branches to grab, so it must be assuming it's added in there already.

**Comment by ndawe** [comment]
There is no such thing as a "weight branch". That's purely semantic. Branches are branches. If one happens to be interpreted as a weight by you then that makes it a "weight branch" to you. include_weight and weight_name provide a way to include the tree.GetWeight() as a column in the output array. That's all.

**Comment by ndawe** [comment]
This is now clarified in the docs: http://scikit-hep.org/root_numpy/reference/generated/root_numpy.root2array.html#root_numpy.root2array

```
     include_weight : bool, optional (default=False)
-        Include a column containing the tree weight.
+        Include a column containing the tree weight ``TTree::GetWeight()``.
+        Note that this will be the same value for all entries unless the tree
+        is actually a TChain containing multiple trees with different weights.
```

**Comment by vlisovsk** [comment]
Well, thank you for the explanation. I actually thought this was supposed to be per-event weight (different for each entry in the tree) but not the global weight to the whole tree.

**Comment by ndawe** [comment]
No problem @vlisovsk! Thanks for bringing this up. The docs have now improved as a result :smile:
