### ISSUE TITLE
Reading vector branches

### ISSUE THREAD

**Issue by fyuuhi** [scikit-hep/root_numpy#359]
I tried to read vector branches and problem occured.
"electron' is vector< double > branches and index of electron means (x, y, z) like below.
```py
array1 = tree2array(tree1, branches = ['electron', 'muon', 'tau'])
```
```
electron[0] --->>> x
electron[1] --->>> y
electron[2] --->>> z
```
I want to draw histgram of electron x. 
```py
array1['electron'][0]
```
is not electron x and is (x, y ,z) for first events. So any idea to draw electron x for all events?

Best regards.

**Comment by kratsg** [comment]
What problem did you get? Recall that your structure is an `ndarray` of `n` events. Can you give more details on the structure (e.g. what does `print array1` give you and so on...)

**Comment by fyuuhi** [comment]
Hi kartsg,

(python version is 2.7.13)

"electron" is vector< double > branch and print() result is below (n is full event number).
```python
print(array1.dtype)
>>> [('electron','O')]

print(array1.ndim)
>>> 1

print(array1.shape)
>>> (n,)

print(array1['electron'].dtype)
>>> object

print(array1['electron'].shape)
>>> (n,)

print(array1['electron'][0])
>>> [x_0, y_0, z_0]
```

what I want:
```python
[x_0, x_1, x_2, x_3, ..., x_n]
```
I got, but not want:
```python
print(array1['electron'][:][0])
>>> [x_0, y_0, z_0]
```
I got, but not enough:
```python
print(array1['electron'][0][0])
>>> x_0
print(array1['electron'][1][0])
>>> x_1
print(array1['electron'][2][0])
>>> x_2
```
I got what I want, but a bit late to run:
```python
print([array1['electron'][ii][0] for ii in range(n)]) 
>>> [x_0, x_1, x_2, ...,x_n]
```
In ROOT CINT, `tree -> Draw("electron[0]"])` enable to get and draw [x_0, x_1, x_2, ..., x_n] quickly (maybe no need for loop), but I don't know do that quickly in root_numpy. So would you help me?

Best regards,

**Comment by kratsg** [comment]
@fyuuhi -- is there a way you can send me the ROOT file? I want to see what your tree looks like. I'm having a hard time following.

**Comment by eduardo-rodrigues** [comment]
The work can be done with `uproot`, which now effectively superseded this package. And the author hasn't replied for 1.5 years. I reckon we can now close this, @kratsg.
