### ISSUE TITLE
Duplicate branches issue

### ISSUE THREAD

**Issue by pmendiol** [scikit-hep/root_numpy#360]
Whenever I try to run my script, it raises an error as follows:
 File "ApplyRegWeights.py", line 48, in <module>   
  data_xgb1   = root2array(directory,what_tree,branch_names_xgb1)                                                                                               File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-pippkgs_depscipy/3.0-njopjo6/lib/python2.7/site-packages/root_numpy/_tree.py", line 231, in root2array    warn_missing_tree)                                                                                                                                            File "root_numpy/src/tree.pyx", line 605, in _librootnumpy.root2array_fromfile (root_numpy/src/_librootnumpy.cpp:605)                                           File "root_numpy/src/tree.pyx", line 279, in _librootnumpy.tree2array (root_numpy/src/_librootnumpy.cpp:279)                                                  ValueError: duplicate branches requested . 

I have several root files with names "minitree_13TeV_G_m250.root,...., minitree_13TeV_R_m250.root..., minitree_13TeV_N_node0.root,...." How to fix this? Thanks a lot!

A portion of my script is as follows:

type = ["G", "R", "N"]
for a in range(len(type)):  

	if type[a] == "G" or "R":
		point = ["m250","m260","m270","m280","m300","m320","m340","m350","m400","m450","m500","m550","m600","m650","m700","m750","m800","m900","m1000"]
	else:
		point = ["node0","node1","node2","node3","node4","node5","node6","node7","node8","node9","node10","node11","node12","node12","node13"]

	for b in range(len(point)):

		dir = ROOT.TFile("../2017HHbbgg/2b2g_NoRegression/minitree_13TeV_"+type[a]+"_"+point[b]+".root")
		what_tree = dir.Get("jet")

		branch_names_xgb1 = """jet1Pt,nPVs,jet1Eta,Jet1_mt,Jet1_leadTrackPt,Jet1_leptonPtRel,
		Jet1_leptonPt,Jet1_leptonDeltaR,Jet1_vtxPt,Jet1_vtxMass""".split(",")
		branch_names_xgb1 = [c.strip() for c in branch_names_xgb1]  
		data_xgb1	= tree2array(what_tree, branch_names_xgb1)

**Comment by kratsg** [comment]
Just a quick guess, but you probably have repeated branch names. Can you just try something like...

```
	branch_names_xgb1 = list(set(c.strip() for c in branch_names_xgb1))
```

to remove duplicates?

**Comment by pmendiol** [comment]
That fixed the problem. Thanks a lot!
