### ISSUE TITLE
root_numpy with numpy incompatibility

### ISSUE THREAD

**Issue by othrif** [scikit-hep/root_numpy#363]
Hi, 

I am trying to install root_numpy for the first time and I am running into some difficulty. 
Here is my setup: 
ROOT 6.13/03
NumPy 1.14.2
Python 2.7
macOS

I have done a clean installation: 
pip uninstall numpy root_numpy
pip install numpy root_numpy

When i run: nosetests --exe -s -v root_numpy
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

When i do: python -c "import root_numpy"
/Users/XXXX/Library/Python/2.7/lib/python/site-packages/root_numpy/__init__.py:46: RuntimeWarning: numpy 1.14.2 is currently installed but you installed root_numpy against numpy 1.14.0. Please consider reinstalling root_numpy for this numpy version.
  RuntimeWarning)

I tried a manual installation as well but with the same result. Let me know if you have any ideas of what might be causing this problem or if you need more input from my side.

**Comment by othrif** [comment]
Yes,  PyROOT is installed. 
Even though I have seen "Fatal Python error: PyThreadState_Get: no current thread" when the python version i was running was different than the one installed with root. But I don't have this problem with PyROOT anymore. So I am wondering if it is something related.

**Comment by kratsg** [comment]
Ok, don't run `pip install numpy` here. Do something like `pip install --ignore-installed --upgrade root_numpy`.

Are you using virtual environments?

**Comment by othrif** [comment]
Hmm, still the same, see the message below.

I am not using a virtual environement for this particular application as i had problems installing PyROOT in my virtual environment. For instance, python -c "import ROOT" would work fine for my regular shell but returns this error when i switch to my virtual environment:
python -c "import ROOT"
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6


--- 

/Users/XXX/Library/Python/2.7/lib/python/site-packages/root_numpy/setup_utils.py:111: ImportWarning: Not importing directory 'ROOT': missing __init__.py
  import ROOT
/Users/XXX/Library/Python/2.7/lib/python/site-packages/root_numpy/__init__.py:46: RuntimeWarning: numpy 1.14.2 is currently installed but you installed root_numpy against numpy 1.14.0. Please consider reinstalling root_numpy for this numpy version.
  RuntimeWarning)

**Comment by kratsg** [comment]
Ok, this is a problem with how you set up ROOT. Are you using python2 or python3? ROOT works perfectly fine in virtual environments.

**Comment by othrif** [comment]
I think this is the problem. I have two different python versions used inside vs. outside the virtual environment. 
Inside i have Python 2.7.14 and the path i get is /Users/XXX/.virtualenvs/ROOT/bin/python 
While outside i have Python 2.7.10 and the path i have is /usr/local/bin/python

i can try re-installing python again inside the virtual environment.

**Comment by kratsg** [comment]
Hi, I'm not sure we're talking about the same kind of virtual environment. A virtual environment is *for* a specific version of python. That is, you use something like https://virtualenvwrapper.readthedocs.io/en/latest/ which points at a python binary and simply isolates you from globally installed packages and other virtualenvs with other versions and does all the symlinking correctly. You don't install python in a virtualenvironment.

How/why do you have two very, very similar versions of python? The error you're getting is 100% certainly due to ROOT not being installed correctly because it's not picking up the python that you're using to install packages with.

**Comment by othrif** [comment]
Hey, indeed it was a python version confusion. All resolved now, many
thanks!
