### ISSUE TITLE
Overflow error with 64-bit integers

### ISSUE THREAD

**Issue by andrey-popov** [scikit-hep/root_numpy#366]
Dear developers,

I think I found a bug, which seems to be caused by integer overflows when reading trees with friends. Numbers larger than 2<sup>31</sup> get replaced by -2<sup>31</sup> on read in some cases. Below is a minimal example to reproduce the problem:

```Python
from array import array
import numpy as np
import random
from root_numpy import tree2array
import ROOT


def write():
    f = ROOT.TFile('test.root', 'recreate')
    num_entries = 100
    
    tree1 = ROOT.TTree('T1', '')
    x = array('f', [0.])
    tree1.Branch('x', x, 'x/F')
    
    for i in range(num_entries):
        x[0] = random.random()
        tree1.Fill()
    
    tree2 = ROOT.TTree('T2', '')
    n = array('Q', [0])           # Unsigned 64-bit integers
    tree2.Branch('n', n, 'n/l')   # 
    
    offset = 2 ** 31
    
    for i in range(num_entries):
        n[0] = random.randrange(offset, 2 * offset)
        tree2.Fill()
    
    f.Write()
    f.Close()


def count(tree):
    a = tree2array(tree, branches=['n'])
    m = -2 ** 31
    return np.count_nonzero(a['n'] == m)


if __name__ == '__main__':
    
    random.seed(17)
    write()
    
    f = ROOT.TFile('test.root')
    
    tree = f.Get('T2')
    print(count(tree))
    
    tree.AddFriend('T1')
    print(count(tree))
    
    tree = f.Get('T1')
    tree.AddFriend('T2')
    print(count(tree))
    
    f.Close()
```
The script creates a ROOT file with two trees, each containing a single branch with either floating-point numbers or 64-bit integers. The tree with integer numbers is filled with values not smaller than 2<sup>31</sup>. The trees are then read and converted to a NumPy array, keeping only the branch with integers. This is done in different fashions, and entries equal to -2<sup>31</sup> are counted, and their number is printed out. There should be none, but in the last case all 100 entries get replaced by this value. Here is the output I get from the script with Python 3.5.3, ROOT 6.10.04, and root_numpy 4.7.3:
```
0
0
100
```

Could you please have a look?

**Comment by kratsg** [comment]
Hi, this is not a root_numpy bug. Please note that when reading the friend tree out, numpy is treat it as a `uint8` instead of `uint16` as you expect. To make this work, try doing something like

```python
np.count_nonzero(a['n'].astype(np.uint16) == m)
```

and it'll work fine.

**Comment by andrey-popov** [comment]
@kratsg, thank you for having a look. However, the conversion to `uint32` (I guess this is what you meant) certainly does not seem to me as the expected behaviour. Am I missing something? What is the recommended procedure to deal with friend trees then? Should I always check the types of all branches and supply them to NumPy?

**Comment by kratsg** [comment]
> However, the conversion to `uint32` (I guess this is what you meant) certainly does not seem to me as the expected behaviour.

This is because I checked the behavior in the underlying pyroot and the conversion is there (which makes me think there's an issue with the python binding to ROOT). NB: root_numpy sort-of wraps around this.

**Comment by andrey-popov** [comment]
I'm not sure I'm quite following you. Are you saying there is a bug in PyROOT? Would you mind [reporting it](https://sft.its.cern.ch/jira/secure/CreateIssue.jspa?pid=10010&issuetype=1)?

**Comment by kratsg** [comment]
> I'm not sure I'm quite following you. Are you saying there is a bug in PyROOT?

It looks like it. `root_numpy` is inferring the type from how it's stored in ROOT. If that's somehow stored incorrectly, then `root_numpy` will parse it incorrectly. That said, the business with the friend trees is really tricky. I can't find any lines in the root_numpy code that causes this to happen (since you're using ROOT to add in the friend trees).

**Comment by andrey-popov** [comment]
`tree.GetBranch('n').GetTitle()` in that setup returns the correct type code (`l`), so from what I see the type is stored correctly.

**Comment by kratsg** [comment]
> `tree.GetBranch('n').GetTitle()` in that setup returns the correct type code (`l`), so from what I see the type is stored correctly.

Hi @andrey-popov I know. This is why, as I've explained, we're doing exactly what you might expect root_numpy to do here (https://github.com/scikit-hep/root_numpy/blob/master/root_numpy/src/tree.pyx#L335-L342) and so if there's a problem with the type-conversion, it's because `root_numpy` is being told the wrong type from ROOT, rather than having the wrong converter.

**Comment by andrey-popov** [comment]
Sorry, how do you deduce that `root_numpy` is being told the wrong type by ROOT when `TBranch::GetTitle()` returns the correct type code?

**Comment by kratsg** [comment]
> Sorry, how do you deduce that `root_numpy` is being told the wrong type by ROOT when `TBranch::GetTitle()` returns the correct type code?

Hi @andrey-popov I don't actively maintain root_numpy (currently nobody does). This support is best-of. The reason I say that this will be a problem is because we already have tests defined to check that the expected converter is being picked up for a given type. You can see here that https://github.com/scikit-hep/root_numpy/blob/master/root_numpy/src/converters.pyx converts between the types as expected.

I can debug line-by-line and I see the types being correctly converted as expected for a 64-bit ROOT installed on a 64-bit machine. You can try it out yourself (and see what numpy treats for types and what ROOT treats and how things are converted back and forth). I've already provided a solution to fix it.

Additionally, your code shows unsigned ints being explicitly converted to longs (your comment about unsigned 64-bit isn't completely correct) so it's not clear what the correct conversion is here. If you really want to see how root_numpy is converting things, try out this very simple code:

```python
import ROOT
import root_numpy as rnp
import array

tree = ROOT.TTree('mytree', '')
arrays = []
typemap = [
    ('b', 'B', 'signed_char'),
    ('B', 'b', 'unsigned_char'),
    ('h', 'S', 'signed_short'),
    ('H', 's', 'unsigned_short'),
    ('i', 'I', 'signed_int'),
    ('I', 'i', 'unsigned_int'),
    ('l', 'L', 'signed_long'),
    ('L', 'l', 'unsigned_long'),
    ('f', 'F', 'float_32b'),
    ('d', 'D', 'float_64b')
]

for pytype, rootype, name in typemap:
    n = array.array(pytype, [0])
    arrays.append(n)
    tree.Branch(name, n, '/'.join([name, rootype]))

dtypes = rnp.tree2array(tree).dtype.fields
fmtStr = '{0:20s}{1:20s}{2:20s}{3:20s}'
print(fmtStr.format('pytype', 'rootype', 'name', 'numpy_dtype'))
for pytype, rootype, name in typemap:
    print(fmtStr.format(pytype, rootype, name, dtypes[name][0]))
```
which outputs

```
pytype              rootype             name                numpy_dtype         
b                   B                   signed_char         int8                
B                   b                   unsigned_char       uint8               
h                   S                   signed_short        int16               
H                   s                   unsigned_short      uint16              
i                   I                   signed_int          int32               
I                   i                   unsigned_int        uint32              
l                   L                   signed_long         int64               
L                   l                   unsigned_long       uint64              
f                   F                   float_32b           float32             
d                   D                   float_64b           float64             
```

Please note that the conversion between python's `array.array` type codes and numpy's type codes and ROOT's type codes are not very trivial or obvious.

**Comment by andrey-popov** [comment]
You are basically saying that this is not a bug because `root_numpy` is supposed to treat the conversions correctly. I understand that it *should* work, but I'm giving an example when it doesn't. This means there is something wrong somewhere, and at this point there is no indication that the problem is in PyROOT since it does report the correct type. Also, accessing tree entries in pure PyROOT like in
```python
for entry in tree:
    print(entry.x, entry.n)
```
gives correct the results.

> I've already provided a solution to fix it.

I don't think that doing a manual type casting on top of `root_numpy` is a satisfactory solution to the problem. In addition to being inconvenient, I can never be sure that the underlying problem does not manifest itself in a more serious but subtle way. E.g. what if under some circumstances it will cut off the remaining 4 bytes?

> your comment about unsigned 64-bit isn't completely correct

I've checked it again and don't see anything wrong there.

I totally get that `root_numpy` is not fully supported, and I don't necessarily expect you to fix the problem. But maybe you shouldn't close a valid bug report.

**Comment by kratsg** [comment]
> I've checked it again and don't see anything wrong there.

You're using `Q` here, so you will need to confirm that your platform C compiler supports `long long` (but ROOT doesn't so you need to decide how to convert `long long` to `long` or leave that up to ROOT). Did you run my script above? Here's one that reproduces the behavior you're seeing, but it has nothing to do with root_numpy or the trees themselves.

```python
import ROOT
import root_numpy as rnp
import array
import tempfile

tfile = tempfile.NamedTemporaryFile()
f = ROOT.TFile(tfile.name, 'recreate')
tree = ROOT.TTree('mytree', '')
ftree = ROOT.TTree('myfriendtree', '')
arrays = []
typemap = [
    ('b', 'B', 'signed_char'),
    ('B', 'b', 'unsigned_char'),
    ('h', 'S', 'signed_short'),
    ('H', 's', 'unsigned_short'),
    ('i', 'I', 'signed_int'),
    ('I', 'i', 'unsigned_int'),
    ('l', 'L', 'signed_long'),
    ('L', 'l', 'unsigned_long'),
    ('f', 'F', 'float_32b'),
    ('d', 'D', 'float_64b')
]

for pytype, rootype, name in typemap:
    n = array.array(pytype, [1])
    arrays.append(n)
    tree.Branch(name, n, '/'.join([name, rootype]))
    fname = name + '_friend'
    ftree.Branch(fname, n, '/'.join([fname, rootype]))

tree.Fill()
ftree.Fill()

f.Write()

dtypes = rnp.tree2array(tree).dtype.fields
fdtypes = rnp.tree2array(ftree).dtype.fields
fmtStr = '{0:25s}{1:25s}{2:25s}{3:25s}'
print(fmtStr.format('pytype', 'rootype', 'name', 'numpy_dtype'))
for pytype, rootype, name in typemap:
    print(fmtStr.format(pytype, rootype, name, dtypes[name][0]))
    fname = name + '_friend'
    print(fmtStr.format(pytype, rootype, fname, fdtypes[fname][0]))

tree.AddFriend('myfriendtree')
dtypes = rnp.tree2array(tree, branches=[i[2] for i in typemap] + [i[2] + '_friend' for i in typemap]).dtype.fields
fmtStr = '{0:25s}{1:25s}{2:25s}{3:25s}'
print(fmtStr.format('pytype', 'rootype', 'name', 'numpy_dtype'))
for pytype, rootype, name in typemap:
    print(fmtStr.format(pytype, rootype, name, dtypes[name][0]))
    fname = name + '_friend'
    print(fmtStr.format(pytype, rootype, fname, dtypes[fname][0]))

f.Close()
```

where this outputs

```
pytype                   rootype                  name                     numpy_dtype              
b                        B                        signed_char              int8                     
b                        B                        signed_char_friend       int8                     
B                        b                        unsigned_char            uint8                    
B                        b                        unsigned_char_friend     uint8                    
h                        S                        signed_short             int16                    
h                        S                        signed_short_friend      int16                    
H                        s                        unsigned_short           uint16                   
H                        s                        unsigned_short_friend    uint16                   
i                        I                        signed_int               int32                    
i                        I                        signed_int_friend        int32                    
I                        i                        unsigned_int             uint32                   
I                        i                        unsigned_int_friend      uint32                   
l                        L                        signed_long              int64                    
l                        L                        signed_long_friend       int64                    
L                        l                        unsigned_long            uint64                   
L                        l                        unsigned_long_friend     uint64                   
f                        F                        float_32b                float32                  
f                        F                        float_32b_friend         float32                  
d                        D                        float_64b                float64                  
d                        D                        float_64b_friend         float64                  
pytype                   rootype                  name                     numpy_dtype              
b                        B                        signed_char              int8                     
b                        B                        signed_char_friend       int32                    
B                        b                        unsigned_char            uint8                    
B                        b                        unsigned_char_friend     int32                    
h                        S                        signed_short             int16                    
h                        S                        signed_short_friend      int32                    
H                        s                        unsigned_short           uint16                   
H                        s                        unsigned_short_friend    int32                    
i                        I                        signed_int               int32                    
i                        I                        signed_int_friend        int32                    
I                        i                        unsigned_int             uint32                   
I                        i                        unsigned_int_friend      int32                    
l                        L                        signed_long              int64                    
l                        L                        signed_long_friend       int32                    
L                        l                        unsigned_long            uint64                   
L                        l                        unsigned_long_friend     int32                    
f                        F                        float_32b                float32                  
f                        F                        float_32b_friend         float64                  
d                        D                        float_64b                float64                  
d                        D                        float_64b_friend         float64                  
```

The problem in this case is that ROOT isn't telling us that this branch exists when we ask for the tree's list of branches. It is only when you provide the branches specifically that we need to access it from a TTreeFormula (and this is where the type changes occur) -- but it's not determined from the branch type itself.

If you can get the branch shown through a `tree.Print()`, then it can be converted correctly -- otherwise, you have to explicitly pass in the type so that we can convert it properly from a TTreeFormula.

I can try and add in a patch that attempts to grab branches from the tree as if it was an alias, and not a formula, but there's no easy way to handle this case, since this really boils down to how ROOT handles friend trees.

**Comment by andrey-popov** [comment]
Thanks for digging deeper into this. Yes, `long long` is 8 bytes long in the standard C compiler in my system. I ran both your scripts obtaining the same results as yours.

> The problem in this case is that ROOT isn't telling us that this branch exists when we ask for the tree's list of branches.

Then I guess the problem is in [this line](https://github.com/scikit-hep/root_numpy/blob/23cfb9476cb8ec9742363a99641d4bde637298ad/root_numpy/src/tree.pyx#L187), where `root_numpy` gets the list of branches of the tree. `TTree::GetListOfBranches` does not include branches from friend trees, which, as far as I can tell, is the intended behaviour. To obtain the list of branches in all trees, one can do something along these lines instead:
```cython
cdef TObjArray* branch_array = tree.GetListOfBranches().Clone()  #Do not modify original list
for friend in tree.GetListOfFriends():
    branch_array.AddAll(friend.GetTree().GetListOfBranches)
```
Or avoid dealing with a `TObjArray` altogether:
```cython
branch_list = [b for b in tree.GetListOfBranches]
for friend in tree.GetListOfFriends():
    branch_list += [b for b in friend.GetTree().GetListOfBranches()]
```
and adjust the other two places where `branch_array` is used.

What do you think?

**Comment by kratsg** [comment]
> which, as far as I can tell, is the intended behaviour.

Hard to say. Aliases also do not show up in this list -- but are retrievable with "GetListOfAliases" or something similar. I can probably adjust the code to use `branch_array` and fix it in master, but I don't have permissions to create releases -- and I'm not sure any new releases on pypi will be created for `root_numpy`.

**Comment by andrey-popov** [comment]
> I can probably adjust the code to use `branch_array` and fix it in master, but I don't have permissions to create releases -- and I'm not sure any new releases on pypi will be created for `root_numpy`.

Sad to hear this. Are you saying that the project is dead, and users should migrate from it? Would you mind mentioning this in the README then, so that people don't waste their time?
