### ISSUE TITLE
Link to ROOT libs without version numbers in the path

### ISSUE THREAD

**Issue by abmorris** [scikit-hep/root_numpy#367]
I have `root_numpy` installed via `pip` and `root` installed via `dnf`.

When I upgrade `root` between the second-most-major version numbers (e.g. `6.12` to `6.14`) I get this kind of error when importing `root_numpy`:

    ImportError: libCore.so.6.12: cannot open shared object file: No such file or directory

which I fix by reinstalling `root_numpy`. I shouldn't have to do this, though. It should link to `libCore.so`.

**Comment by kratsg** [comment]
Hi @abmorris -- you have to recompile `root_numpy` if you change/update your root installation. This is expected.
