### ISSUE TITLE
problems with root_numpy setup from cvmfs

### ISSUE THREAD

**Issue by vmagerl** [scikit-hep/root_numpy#370]
Hi,

currently I am migrating the central fitter and plotter tool of our analysis group to use root_numpy from cvmfs. 
Until yesterday evening everything worked really well including the usage of root_numpy in combination with ipython to run some small explanatory examples and also for debugging purposes.
Unfortunately today it's not possible anymore to even open an ipython session or to run the scripts relying on root_numpy.

I'm using the following setup
`setupATLAS
lsetup root "lcgenv -p LCG_87 x86_64-slc6-gcc62-opt pip"`

which now results in:
`Traceback (most recent call last):
  File "/home/vm1023/.local/bin/ipython", line 7, in <module>
from IPython import start_ipython
  File "/home/vm1023/.local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/vm1023/.local/lib/python2.7/site-packages/IPython/core/application.py", line 16, in <module>
    from copy import deepcopy
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/Python/2.7.15/x86_64-slc6-gcc62-opt/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/Python/2.7.15/x86_64-slc6-gcc62-opt/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref`

when trying to open ipython and 

`Traceback (most recent call last):
  File "testImport.py", line 1, in <module>
    import root_numpy
  File "/home/vm1023/.local/lib/python2.7/site-packages/root_numpy/__init__.py", line 51, in <module>
    from ._tree import (
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/ROOT/6.14.04/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/vm1023/.local/lib/python2.7/site-packages/root_numpy/_tree.py", line 6, in <module>
    from . import _librootnumpy
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/ROOT/6.14.04/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: /home/vm1023/.local/lib/python2.7/site-packages/root_numpy/_librootnumpy.so: undefined symbol: _ZN5TTreeC1EPKcS1_i`

when trying to run some python script importing root_numpy.

I'm not sure, if this is really an issue related to root_numpy or if it's a general problem with the release I'm using. Anyway, it really puzzles me, that this errors show up all of a sudden. I'm seeing it on the local clusters of my home institute as well as on lxplus.

Any help is highly appreciated!
Cheers,
Veronika

**Comment by kratsg** [comment]
Hi, this is a very ATLAS-specific question, but you're lucky I'm in ATLAS

> I'm not sure, if this is really an issue related to root_numpy or if it's a general problem with the release I'm using. Anyway, it really puzzles me, that this errors show up all of a sudden. I'm seeing it on the local clusters of my home institute as well as on lxplus.

`lsetup root "lcgenv -p LCG_87 x86_64-slc6-gcc62-opt pip"`

The problem with this command is that it will always set up the latest ROOT, which can change and not be the one that `root_numpy` was initially installed against. You will want to reinstall root_numpy, but you should be able to just run

`lsetup "lcgenv -p LCG_87 x86_64-slc6-gcc62-opt root_numpy"`

to get what you need, I think. Can I ask what you need `root_numpy` for? I will encourage you to switch to using [uproot](https://github.com/scikit-hep/uproot) which doesn't need ROOT and can open/access ROOT files for you.

**Comment by vmagerl** [comment]
Hi Gordon,

thanks a lot for your quick reply. Indeed just running lsetup with root_numpy added works partially. So the scripts seem to run again. Unfortunately ipython doesn’t but that seems to be just another version problem...

To answer your question, we were using root_numpy for the ATLAS SUSY analysis challenge and were really impressed how easy and fast it was, so we decided to use it also for our main plotting tool. That is to produce all the kinematic distributions, like the “n-1 plots”, to also do the data/MC comparison in the signal and control regions, which was done previously using only TTree.Draw() with arbitrary complex selections. I was not aware the root_numpy is deprecated/not maintained any longer. Switching to uproot might be a possibility but probably not on a short time scale. Thanks a lot for the suggestion though, I will definitely look into it.

cheers,
Veronika
