### ISSUE TITLE
Proper way to use array2root if one element of the array is an array

### ISSUE THREAD

**Issue by ViacheslavLi** [scikit-hep/root_numpy#376]
Is there a way to store an array, one element of which is an array itself? For example, something like this:
[( 0.1, 3, array([1000, 2000, 3000], dtype=uint16), 5)
( 0.2, 1, array([5000, 6000, 7000], dtype=uint16), 4)
]

The arrays within the main array are skipped (not stored) in the root file, using root_numpy.array2root(arr, rootfilename, mode='recreate'). Everything else is properly stored though.

**Comment by kratsg** [comment]
You're going to need to format it as a numpy array for `array2root` to work, and in particular, in a shape that `numpy` is generally happy with. This gets really tricky with multi-dimensional (non-regular) shapes and you usually have to store them as objects, e.g. your above example is only convertible to a numpy array as

```python
Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import root_numpy as rnp
>>> import numpy as np
>>> a = np.array([( 0.1, 3, [1000, 2000, 3000], 5), ( 0.2, 1, [5000, 6000, 7000], 4)], dtype=[('col1', np.float64), ('col2', np.uint64), ('col3', np.object), ('col4', np.uint64)])
>>> a
array([(0.1, 3, list([1000, 2000, 3000]), 5),
       (0.2, 1, list([5000, 6000, 7000]), 4)],
      dtype=[('col1', '<f8'), ('col2', '<u8'), ('col3', 'O'), ('col4', '<u8')])
>>> rnp.array2root(a, 'test.root', mode='recreate')
/Users/kratsg/.virtualenvs/numpythia/lib/python2.7/site-packages/root_numpy/_tree.py:633: UserWarning: converter for dtype('O') is not implemented (skipping)
  _librootnumpy.array2root(arr, filename, treename, mode)
```

but we can't dump objects into ROOT trees because there's no good type-matching for this. Instead, you want to do something like

>>> a = np.array([( 0.1, 3, [1000, 2000, 3000], 5), ( 0.2, 1, [5000, 6000, 7000], 4)], dtype=[('col1', np.float64), ('col2', np.uint64), ('col3', np.uint64, (3,)), ('col4', np.uint64)])
>>> a
array([(0.1, 3, [1000, 2000, 3000], 5), (0.2, 1, [5000, 6000, 7000], 4)],
      dtype=[('col1', '<f8'), ('col2', '<u8'), ('col3', '<u8', (3,)), ('col4', '<u8')])
>>> rnp.array2root(a, 'test.root', mode='recreate')
>>> rnp.root2array('test.root')
array([(0.1, 3, [1000, 2000, 3000], 5), (0.2, 1, [5000, 6000, 7000], 4)],
      dtype=[('col1', '<f8'), ('col2', '<u8'), ('col3', '<u8', (3,)), ('col4', '<u8')])
```

Note the extra special nested dtype we're using here: `('col3', np.uint64, (3,))` instead of the object dtype. This lets us dump that back into a root file as you expect.

**Comment by ViacheslavLi** [comment]
Thank you. This makes sense. I have a ROOT file which I would like to sort in python, and then to store it back in ROOT format. So, the numpy array is created with root2array (which works properly).

wy = root_numpy.root2array(filename,treename='W')
root_numpy.array2root(wy, filename2, mode='recreate')

wy is structured as in my original post; however, when I try to store it back to ROOT file, all the array-like elements of the array are not stored.
I get the same "UserWarning" as in your post.
/usr/lib64/python2.7/site-packages/root_numpy/_tree.py:633: UserWarning: converter for dtype('O') is not implemented (skipping)
  _librootnumpy.array2root(arr, filename, treename, mode)

In the original root file
W->Show(10)
======> EVENT:10
 a       = 271.972
 b         = 2
 c          = 320
 d        = 1000, 2000, 3000
 e       = 4

In the final root file
tree->Show(10)
======> EVENT:10
 a       = 271.972
 b         = 2
 c          = 320
 e       = 4

^ no "d" branch.

**Comment by kratsg** [comment]
You should see the dtypes for `wy` and change the objects to non-objects. What `root_numpy` are you working with since it should at least load things in correctly. If the length of vectors in `d` is not-constant, then you can only load it as an object and there's no easy way to write it back...

**Comment by kratsg** [comment]
> 4.7.3 is the version of root_numpy that I am using. The "d" is fixed length.
> I guess it is becoming more numpy question at this point.
> 
> wy.astype([('a', '<f8'), ('b', '<u2'), ('c', '<u2'), ('d, '<u8', (3,)), ('e', '<u4')])
> ValueError: setting an array element with a sequence.

I don't know what else is missing, but it looks like you have a non-fixed length for `d` here. This is a numpy question at this point.
