### ISSUE TITLE
Vector of TLorentzVectors

### ISSUE THREAD

**Issue by mariel-pettee** [scikit-hep/root_numpy#377]
Hi all, I'm attempting to use root_numpy to read in some .root files with several branches (e.g. "taus_p4") that are vectors of TLorentzVectors. I saw in #141 that the ability to read vector branches was implemented for several common types. Is it possible to implement this with TLorentzVectors as well? 

Thanks very much for your time!

**Comment by kratsg** [comment]
@mariel-pettee you'll have to realize that TLorentzVectors are purely a ROOT-based constructor. `root_numpy` converts all of these things to `numpy` data-type equivalents. Reading out a vector means converting it to a list (a C-array) but a TLorentzVector does not have an equivalent native data structure.

If this is something you want to do, [scikit-hep/uproot](https://github.com/scikit-hep/uproot) (cc @jpivarski) is probably a better project for you to look at.

**Comment by mariel-pettee** [comment]
Hi Giordon, thanks for your quick and helpful reply! Indeed, uproot did the trick for me :)
