### ISSUE TITLE
TFormula test fails with ROOT 6.16.00

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/root_numpy#379]
Found in #378, see this CI build log: https://travis-ci.org/scikit-hep/root_numpy/jobs/486522395#L1307

**Comment by eduardo-rodrigues** [comment]
I believe this can be closed now, right @chrisburr?

**Comment by chrisburr** [comment]
No it's still an issue, see #389

**Comment by eduardo-rodrigues** [comment]
I see. Indeed one needs a new release for the newest versions of ROOT with that change in TFormula …

**Comment by eduardo-rodrigues** [comment]
The package is deprecated. Closing as won't do.
