### ISSUE TITLE
importing the root_numpy in python 

### ISSUE THREAD

**Issue by BinishB** [scikit-hep/root_numpy#382]
Hi catching up the same issue. I have the problem while importing the root_numpy in python environment. What I get is

Traceback (most recent call last):
File "", line 1, in
File "/home/binish/.local/lib/python2.7/site-packages/root_numpy/init.py", line 51, in
from ._tree import (
File "/home/binish/root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3/root/lib/ROOT.py", line 461, in _importhook
return _orig_ihook( name, *args, **kwds )
File "/home/binish/.local/lib/python2.7/site-packages/root_numpy/_tree.py", line 6, in
from . import _librootnumpy
File "/home/binish/root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3/root/lib/ROOT.py", line 461, in _importhook
return _orig_ihook( name, *args, **kwds )
File "init.pxd", line 872, in init _librootnumpy
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by kratsg** [comment]
You need to provide more information. What does `pip list` show? Are you in a virtual environment? Mac, linux? etc.

**Comment by BinishB** [comment]
Ubuntu 18.04
no I am not using virtual

pip list ====

Package                            Version
---------------------------------- -----------
absl-py                            0.6.1
asn1crypto                         0.24.0
astor                              0.7.1
awkward                            0.7.1
backports-abc                      0.5
backports.functools-lru-cache      1.5
backports.shutil-get-terminal-size 1.0.0
backports.weakref                  1.0.post1
bleach                             3.0.2
cachetools                         3.0.0
configparser                       3.5.0
cryptography                       2.1.4
cycler                             0.10.0
decorator                          4.3.0
defusedxml                         0.5.0
distro                             1.3.0
entrypoints                        0.2.3
enum34                             1.1.6
funcsigs                           1.0.2
functools32                        3.2.3.post2
futures                            3.2.0
gast                               0.2.1.post0
grpcio                             1.17.1
h5py                               2.9.0
httplib2                           0.12.0
idna                               2.6
ipaddress                          1.0.17
ipykernel                          4.10.0
ipython                            5.8.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.2
Jinja2                             2.10
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
Keras                              2.2.4
Keras-Applications                 1.0.6
Keras-Preprocessing                1.0.5
keyring                            10.6.0
keyrings.alt                       3.0
kiwisolver                         1.0.1
launchpadlib                       1.10.6
lazr.restfulclient                 0.14.2
lazr.uri                           1.0.3
Markdown                           3.0.1
MarkupSafe                         1.0
matplotlib                         2.2.3
mistune                            0.8.4
mock                               2.0.0
nbconvert                          5.4.0
nbformat                           4.4.0
notebook                           5.7.0
numpy                              1.15.4
oauthlib                           2.1.0
pandas                             0.23.4
pandocfilters                      1.4.2
pathlib2                           2.3.2
pbr                                5.1.1
pexpect                            4.6.0
pickleshare                        0.7.5
pip                                19.0
prometheus-client                  0.4.2
prompt-toolkit                     1.0.15
protobuf                           3.6.1
ptyprocess                         0.6.0
pycrypto                           2.6.1
Pygments                           2.2.0
pygobject                          3.26.1
pyparsing                          2.2.2
python-dateutil                    2.7.3
python2                            1.2
pytz                               2018.5
pyxdg                              0.25
PyYAML                             3.13
pyzmq                              17.1.2
qtconsole                          4.4.2
root-numpy                         4.8.0
scandir                            1.9.0
scikit-learn                       0.20.0
scipy                              1.1.0
SecretStorage                      2.3.1
Send2Trash                         1.5.0
setuptools                         39.0.1
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
sklearn                            0.0
subprocess32                       3.5.3
tensorboard                        1.12.2
tensorflow                         1.12.0
termcolor                          1.1.0
terminado                          0.8.1
testpath                           0.4.2
testresources                      2.0.1
tornado                            5.1.1
tqdm                               4.31.1
traitlets                          4.3.2
unity-lens-photos                  1.0
uproot                             3.3.2
uproot-methods                     0.3.3
wadllib                            1.3.3
wcwidth                            0.1.7
webencodings                       0.5.1
weightedstats                      0.3
Werkzeug                           0.14.1
wheel                              0.30.0
widgetsnbextension                 3.4.2

**Comment by BinishB** [comment]
I am able to successfully do 

Import ROOT
Import root_numpy 
but whenever I import root_numpy in python environment it complains the above error.


one more thing on the top of that 

pip install --user root_numpy gives an error 

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/binish/.local/lib/python2.7/site-packages/pip-19.0.dist-info/METADATA'

**Comment by kratsg** [comment]
You need to clean out your site-packages folder at this point. Looks like it's complaining about some junk and so on. E.G. remove existing numpy/root_numpy things.

**Comment by BinishB** [comment]
how can I clean them completely ?

**Comment by kratsg** [comment]
You can `rm` the distributions/folders specifically. I would also encourage you to use virtual environments... https://virtualenvwrapper.readthedocs.io/en/latest/

**Comment by eduardo-rodrigues** [comment]
Can this be closed at this stage, @BinishB and @kratsg?

**Comment by BinishB** [comment]
@Eduardo Rodrigues Well I could not fix the problem but if you want you can close. I am not working anymore this direction.

**Comment by eduardo-rodrigues** [comment]
Thanks @BinishB for the quick response. Sorry to hear that. Maybe you are using `uproot`, which is effectively superseding this package for most functionality (not all so far).

Note that in the meantime ROOT was made available on conda-forge, and that may be a nicer way for you to work ...
