### ISSUE TITLE
Manual Install Error

### ISSUE THREAD

**Issue by carlos-pereyra** [scikit-hep/root_numpy#386]
After inspecting many of the previous install root_numpy issues, it seems that it is not clear which dependencies are required. I'm on MacOS 10.13.6 

Compiler:
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

When I try to setup the build
`git clone git://github.com/rootpy/root_numpy.git`
`cd root_numpy`
`python setup.py install --user`

I get the following error.

`copying root_numpy/config.json -> build/lib.macosx-10.6-x86_64-2.7/root_numpy
running build_ext
building 'root_numpy._librootnumpy' extension
gcc -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iroot_numpy/src -I/anaconda2/include/python2.7 -I/anaconda2/lib/python2.7/site-packages/numpy/core/include -c root_numpy/src/_librootnumpy.cpp -o build/temp.macosx-10.6-x86_64-2.7/root_numpy/src/_librootnumpy.o -pthread -stdlib=libc++ -std=c++11 -m64 -I/usr/local/Cellar/root/6.14.06/include/root -Wno-unused-function -Wno-write-strings
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'gcc' failed with exit status 1
`

**Comment by kratsg** [comment]
Is there a reason you need to install from master of github? Try doing something like `xcode-select --install`. `brew doctor` might be able to identify issues as well.

**Comment by eduardo-rodrigues** [comment]
Getting back to this: @carlos-pereyra, I see you refer to `github.com/rootpy/root_numpy.git` above. Are you really taking root_numpy from the old org? Did you get any further here? In any case, same as for your other post, I would suggest that you get in touch with as many people as possible via the Gitter or the forum at http://scikit-hep.org/get-in-touch.html.

**Comment by carlos-pereyra** [comment]
@kratsg and @eduardo-rodrigues thank you very much for your replies. 

@kratsg  I'll begin by trying `xcode-select --install. brew doctor`

@eduardo-rodrigues I did not realize `github.com/rootpy/root_numpy.git` is the old organization. Is there a newer organization? Thanks.

**Comment by kratsg** [comment]
@carlos-pereyra , this is the newer one.

**Comment by eduardo-rodrigues** [comment]
Yeah, just look at the URL, which should be https://github.com/scikit-hep/root_numpy/issues/386 ;-). Ypu can see the Scikit-HEP org has many packages as its toolset, see the top-level URL …

BTW, maybe you will be interested in join us, community, see the details on the forum and the Gitter channel at http://scikit-hep.org/get-in-touch.html?

**Comment by eduardo-rodrigues** [comment]
Oops, sorry, I had already said this all LOL! Getting old it seems … ;-)

**Comment by eduardo-rodrigues** [comment]
@carlos-pereyra, you no longer updated this issue. Did you get things up and running in the end? Can we close this? Thanks.

**Comment by eduardo-rodrigues** [comment]
Closing this issue since all seems OK. Feel free to reopen, if needed.
