### ISSUE TITLE
tree2array not accepting smart pointer

### ISSUE THREAD

**Issue by ademus4** [scikit-hep/root_numpy#388]
This may be ignorance on my part, but I get 

*** TypeError: tree must be a ROOT.TTree

If using root_numpy.tree2array with a smart pointer to a TTree. 

Am I doing something wrong here? Is there a step I'm missing or should the fact the object is a smart pointer not actually matter in the implementation? 

```
ipdb> test
<ROOT.shared_ptr<TTree> object at 0xb644b90>
ipdb> rnp.tree2array(test)
*** TypeError: tree must be a ROOT.TTree
ipdb> 
```

**Comment by kratsg** [comment]
Most likely this wasn't supported -- can you dereference? Is there a reason you're doing shared pointers here?

**Comment by ademus4** [comment]
What do you mean by dereference? I'm sure there's a reason behind the shared pointers but not my code!

**Comment by kratsg** [comment]
Well, Python doesn't know how to handle shared pointers -- which is the big deal here. I don't know which code you're using to somehow get a shared pointer, but they're certainly doing something non-standard... This is not something root_numpy will handle.
