### ISSUE TITLE
`array2hist` sets entries as the array length.

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/root_numpy#391]
Entries should indicate the number of values used to build the array. Instead we're setting it to the number of binds (the array length)
https://github.com/scikit-hep/root_numpy/blob/e0dd5898a6f7c25e1c80c12bd92abc959b851666/root_numpy/_hist.py#L423

**Comment by kratsg** [comment]
I'm not sure I understand the confusion. `_array.size` is the number of values in the array. `THX.GetEntries()` should represent the number of values in the histogram. This is perfectly compatible?

**Comment by agoose77** [comment]
`THXGetEntries` should reflect the number of times `Fill` was called to add a value (effectively). `array2hist` takes an array of the bin contents, and sets the histogram bins directly, so for a fixed sized array the number of entries is always the same. I believe that we should instead instead be doing `THX.SetEntries(array.sum())`.

For example:
![image](https://user-images.githubusercontent.com/1248413/60729818-8123ba80-9f3b-11e9-8a72-698a14edaa9d.png)

**Comment by kratsg** [comment]
That information doesn't get preserved between the two. `array2hist` is filling an entry per bin, if the array is treated as binned content. Imagine instead I filled the first array 120 times with non-zero (and non-unity) weights -- then array.Sum() would give an inaccurate number as well. Your example only works if the weights are 1. They aren't always 1.

**Comment by agoose77** [comment]
Yes, I meant to include this caveat in my last, apologies. I've thought about it some more, and perhaps we just leave it to the user to call `SetEntries` themselves, if they wish (and are able) to specify it?

**Comment by kratsg** [comment]
So the default definition of arrays to be fed in are the values -- not the binned values. Therefore the current implementation is what makes the most sense. Feeding in `[1, 1, 1, 2, 3]` for the above example gives a histogram with `[0, 3, 1, 1, 0, ....., 0]`. There are 5 entries in the array, and SetEntries() will use the size of the array which is 5 correctly. This is how users expect it to work.

If you want to look at using a different alternative, look into https://github.com/scikit-hep/uproot

**Comment by agoose77** [comment]
Based upon the use of `THX.Fill`, each call to fill increments the entry count, so I would expect that `GetEntries()` reflects the number of "contributions" to the histogram. I realise that this is pretty intractable though, because the array as-is does not include this information, which was why I suggested an argument. I'm not sure that it's really worth the debate though; if you're happy with the current behaviour, then let's close the issue :)
