### ISSUE TITLE
root_numpy should not unconditionally copy THn<T>

### ISSUE THREAD

**Issue by anerokhi** [scikit-hep/root_numpy#392]
Currently, `root_numpy.hist2array` always copies `THn<T>` histograms, even though `THn<T>::fArray::fData` could be adopted as ndarray buffer.

**Comment by eduardo-rodrigues** [comment]
At this point in time the package has been deprecated for quite a while, as displayed on the README. Please move to using https://uproot.readthedocs.io/en/latest/ and https://github.com/scikit-hep/awkward-1.0, which go well beyond what root_numpy could do in many ways.
