### ISSUE TITLE
Add deprecation notice

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/root_numpy#397]
Following on from the last meeting and @eduardo-rodrigues's comment (https://github.com/scikit-hep/root_pandas/pull/30#issuecomment-557047364). I think we've agreed that `root_numpy` is deprecated in favour of `uproot` (or possibly experimental PyROOT).

I propose to add a notice to the README. We could also consider making a new release which raises a deprecation warning on import. Any thoughts?

Alternatively, if someone is interested in taking over maintenance (e.g. fixing #379 and #384), please speak up!

Pinging @kgizdov @ramankhurana @anerokhi as you've "recently" opened issues against `root_numpy`.

**Comment by kgizdov** [comment]
Give me a couple of weeks to have a look. Is that ok?

**Comment by anerokhi** [comment]
@chrisburr thanks for the ping. I've stopped using `root_numpy` and use `uproot` + `numpy` (for everything except for writing to files) and `ROOT` (to write results).  
(It is not hard to write `hist.Set(array.size, array.ravel())` instead of `root_numpy.array_to_hist(...)`.)

**Comment by chrisburr** [comment]
@kgizdov I'm happy with that but I'll let the others comment.

@anerokhi Great :smile: Also uproot can probably write your histograms directly (as well as flat trees) [see here](https://github.com/scikit-hep/uproot#writing-histograms).

**Comment by anerokhi** [comment]
@chrisburr I need nested directories.

**Comment by kratsg** [comment]
@anerokhi -- you can still do that if your names include `a/nested/directory` usually...

**Comment by anerokhi** [comment]
@kratsg https://github.com/scikit-hep/uproot/issues/138

**Comment by ramankhurana** [comment]
Dear Chris

Seems I have missed this notification originally. Do we still have some
time before it is depreciated? I think it will take us a few days to move
the code to uproot. And want to make sure things are ok there,

Regards
Raman Khurana

**Comment by chrisburr** [comment]
The deprecation doesn't involve anything changing, just explicitly writes the current state of things.

It's been several years since anybody was actively maintaining `root_numpy` and nobody has shown any interest in fixing the bugs that have been found with newer ROOT versions so it's better to be explicit in the README so people are aware.
