### ISSUE TITLE
array2tree, array2root error

### ISSUE THREAD

**Issue by CaetanoE** [scikit-hep/root_numpy#405]
Hi all, I did a simple reweighting script and my final objective is to save the weights obtained to an existing root file but the array2tree or array2root seems to fail in this purpose.

 For context, I have the weights in a ndarray called `folding_weights `and a root file in which I want to add the new weights branch called `"MC.root"`. I tried the following:

`f = TFile.Open("MC.root","UPDATE")`
`myTree = f.Get("DecayTree")`
`root_numpy.array2tree(folding_weights, tree= myTree)`

and aso:

` root_numpy.array2root(folding_weights,"MC.root",treename="DecayTree" )`

The best I can get from this is the following error from which I can scape.

`TypeError: object of type 'NoneType' has no len()`

Thank you all for your time, I hope this has and easy solution.

**Comment by kratsg** [comment]
Can you use https://uproot.readthedocs.io/en/latest/ instead? `root_numpy` isn't going to be that well-maintained anymore and all of this functionality is existing in this new package that doesn't depend on root.

**Comment by CaetanoE** [comment]
Okey, I will take a look.

Thanks

**Comment by kratsg** [comment]
You can see details about the deprecation of this package here: https://github.com/scikit-hep/root_numpy#warningroot_numpy-is-deprecated-and-unmaintainedwarning
