### ISSUE TITLE
Fails to build against ROOT 6.26.0

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/root_numpy#406]
See https://github.com/conda-forge/root_numpy-feedstock/pull/32.

I currently don't plan to try and patch it at this time. If a demand shows up I might propose removing everything in `root_numpy.tmva` rather than trying to fix it.

**Comment by eduardo-rodrigues** [comment]
This sounds like a pragmatic and fair approach at this point in time.

It would be interesting to understand who exactly is still relying on root_numpy rather than the uproot series ...

**Comment by eduardo-rodrigues** [comment]
The package is deprecated. Closing as won't do.
